language: ruby

services:
  - mysql

bundler_args: "--without development --jobs=3"

cache: bundler

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
  - bundle exec rspec --color --require spec_helper --format progress spec
  - bundle exec rubocop

notifications:
  slack: for-my-work-space:LlVPMalPCclBl6gMXgJxtlVR
